# Generated by Django 3.2.4 on 2021-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_order', '0002_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(verbose_name='پرداخت شده/ نشده'),
        ),
    ]
