# Generated by Django 3.2.4 on 2021-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_order', '0003_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.IntegerField(blank=True, max_length=150, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
