# Generated by Django 3.2.4 on 2021-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_products_category', '0001_initial'),
        ('shikonovin_products', '0002_auto_20210616_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shikonovin_products_category.ProductCategory', verbose_name='دسته بندی'),
        ),
    ]
