# Generated by Django 3.2.4 on 2021-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_products_category', '0001_initial'),
        ('shikonovin_products', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shikonovin_products_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
