# Generated by Django 3.2.4 on 2021-06-19 12:05

from django.db import migrations, models
import django.db.models.deletion
import shikonovin_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_products', '0004_auto_20210616_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=shikonovin_products.models.upload_gallery_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shikonovin_products.product', verbose_name='محصول')),
            ],
        ),
    ]
