# Generated by Django 3.2.4 on 2021-06-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_products', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری تصویر', 'verbose_name_plural': 'گالری های تصاویر'},
        ),
    ]
