# Generated by Django 3.2.4 on 2021-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_products', '0002_auto_20210616_1059'),
        ('shikonovin_tags', '0002_auto_20210616_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, to='shikonovin_products.Product'),
        ),
    ]
