# Generated by Django 3.2.4 on 2021-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('tell', models.CharField(max_length=50, verbose_name='تلفن تماس')),
                ('fax', models.CharField(max_length=50, verbose_name='فکس')),
                ('email', models.EmailField(max_length=150, verbose_name='میل')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ی ما')),
                ('copy_right', models.CharField(blank=True, max_length=400, null=True, verbose_name='متن کپی رایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت تنظیمات',
            },
        ),
    ]
