# Generated by Django 3.2.4 on 2021-06-26 11:17

from django.db import migrations, models
import shikonovin_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('shikonovin_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_site',
            field=models.ImageField(blank=True, null=True, upload_to=shikonovin_setting.models.upload_image_path, verbose_name='لوگوی سایت'),
        ),
    ]
